### ISSUE TITLE
any chance on getting acinerella licensed under GPLv2+ instead of only GPLv3?

### ISSUE THREAD

**Issue by basisbit** [astoeckel/acinerella#4]
Hi,
any chance on getting the acinerella project licensed under GPLv2+ instead of only GPLv3? There are bunch of projects which would like to use acinerella, but don't or can't change to GPLv3 yet because of various reasons.

**Comment by astoeckel** [comment]
Hi,

yes, that should be possible. Since Acinerella is only such a slim wrapper library I'm perfectly fine with GPLv2+. Please give me some time to check whether there were any non-trivial contributions by anyone apart from me. If not, I'm going to change the license file and headers and close this issue.
